### ISSUE TITLE
?video= page does not override loop setting

### ISSUE THREAD

**Issue by TazeTSchnitzel** [AniDevTwitter/animeopenings#183]
I may be misremembering, but I think that in the past, if you went to a `?video=` page then openings.moe would always loop the video, rather than continuing to a random one when it finishes.

However, currently, this isn't the case, and it remembers whatever you last had it set to on the site, rather than overriding it. So if I go to https://openings.moe/?video=Opening1-MahouShoujoLyricalNanohaAs for example, when the video completes, it continues to a random video.

**Comment by Yay295** [comment]
In the past, if you went to the main page of openings.moe, whether or not it had `?video=`, it would default to looping. `localStorage` has since been added (commit 160de19, 7 months ago), meaning if you toggle one of the buttons in the bottom left of the page, that state will be saved by your browser across sessions. This happens whether you use `?video=` or not. This could be changed, but I feel it would be more confusing to have things work differently for effectively the same URL.

**Comment by QuadPiece** [comment]
Yay295 is correct. The site didn't store the "loop setting" earlier in `localStorage`. It was never intentional that it forced `?video=` links to loop. The code to remember the loop toggle's value between page visits simply wasn't there in the past.

**Comment by QuadPiece** [comment]
Closed by #218
