### ISSUE TITLE
Show video list on same side but still allow opening as a separate tab

### ISSUE THREAD

**Issue by FichteFoll** [AniDevTwitter/animeopenings#216]
Similarly to #215, sliding the list in from the side (like a sidebar) would allow the video to continue playing while a video is selected.

Ideally, However, it should also be possible to open the list in a separate tab when middleclicking the link.

**Comment by QuadPiece** [comment]
I did consider this a while back when redesigning the hub. In the end I never got around to redesigning the list, as is obvious by its dated look compared to everything else.

Might be worth looking into, but it won't be a small task and mobile responsiveness with a sliding menu (that probably requires static positioning) would most likely be a horrid job. Especially since I do not want to pull some 3rd part library into this. Font Awesome and jQuery are enough dependencies for a front-page.

**Comment by FichteFoll** [comment]
Imo mobile compatibility is more of an afterthought, although not a bad one. I never even considered browsing the side on my phone, but I guess we're all different.

**Comment by QuadPiece** [comment]
@FichteFoll I hate mobile web browsing myself. But sadly, normies do not. According to analytics (Before I broke Piwik months ago), about 30% of our views were from mobile.

And highest bounce rate was iOS devices because they don't support WebM I'd guess, but they deserve this for buying an iOS device :^)

**Comment by QuadPiece** [comment]
This has been implemented in #236 and properly styled with bb46c24dc96ed2b55185438d07e06d15dcab633c.
