### ISSUE TITLE
Subtitles : '!' in style name

### ISSUE THREAD

**Issue by Seipas** [AniDevTwitter/animeopenings#261]
When there is a '!' character in a style name inside a .ass file, fontsizes[font] seem to not initialise correctly, and throw a "F undefined" error at line "F = F[S.toFixed(2)];" of "updateAlignment function. The lines seem to appear outside of the screen in this case.

Here is a file to show this behaviour :  
[exclamation_mark.txt](https://github.com/AniDevTwitter/animeopenings/files/767613/exclamation_mark.txt)
(note that this file doesn't have a "Default" style, that may be part of the problem).

**Comment by Yay295** [comment]
A Default style isn't necessary. It does look like it's the '!', though now that I'm looking for it, I'm not sure how it's handling the spaces either...

**Comment by QuadPiece** [comment]
Fixed by PR #262.

Protip @Yay295: If you wrote "fixes #261" without the issue in the middle it would've been automagic.
Alternatively "closes #x" if you wanna follow the current GitHub trend

ref. https://help.github.com/articles/closing-issues-via-commit-messages/ (Every keyword also works in PRs as of 2013)
