### ISSUE TITLE
First syllabe on some lines don't get colorized

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#306]
As the screenshot shows, the first syllabe on many subs (not all of them) doesn't get colorized during a karaoke.

On some ASS files this problem never occurs for some reason.

Example : 

https://live.karaokes.moe/?video=%20PV%20-JAP%20-%20Penguin%20Highway%20

![firefox_2018-08-25_16-22-31](https://user-images.githubusercontent.com/4531597/44619220-174e7500-a883-11e8-883d-72459e31eaff.png)

The line gets correctly colirzed when it reaches its end though, for some reason.

**Comment by Yay295** [comment]
The problem was actually that a few commits ago I decided to keep all of the transitions in order sorted by their start time. This made it easier to check which transitions needed to be fired. Unfortunately, not all of the times were being given as numbers; some were still strings, and so when I was comparing them, it was comparing them as string instead of numbers and then ended up in the wrong spot.
