### ISSUE TITLE
How to report video issues

### ISSUE THREAD

**Issue by HekutoruMAC** [AniDevTwitter/animeopenings#317]
Is there a way to address database inconsistencies?

For example:

> Ending 1a From Basilisk: Kouga Ninpouchou
> Song: "Hime Murasaki" by Nana Mizuki

Has the video corresponding to:

> Ending 1b From Basilisk: Kouga Ninpouchou
> Song: "Wild Eyes" by Nana Mizuki

Thanks

**Comment by Yay295** [comment]
You can make an issue here, or message us on IRC.

This issue should be fixed in about an hour. It looks like the videos *are* different, but it's the same audio, and this is the second ED not the first. Unfortunately our source apparently missed that, so I don't currently have a version of "Hime Murasaki" to put up.
