### ISSUE TITLE
Some subfiles are cut into two lines

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#323]
Hello, it's been a while :)

We have had a small issue for a while with AO and I just remembered to post about it now.

When we use mpv to display subtitles for karaoke, we get a single line in the ASS : 

![subs1](https://user-images.githubusercontent.com/4531597/75336046-beeaa000-588a-11ea-980a-05898881f193.png)

On AO, it appears cut in two lines : 

![subs2](https://user-images.githubusercontent.com/4531597/75336090-d0cc4300-588a-11ea-9bdc-ee863df05a3c.png)

Note that it seems to happen on Firefox but not on Chrome Mobile for some reason (on Chrome Mobile the line isn't cut)

EDIT: To clarify, the problems appear on both Firefox & Chrome desktop, but not on Chrome mobile

Here's a link to the song/ASS in question on Karaoke Mugen Live : 

http://live.karaokes.moe/?video=92ba6883-3d3a-4664-900f-19c12b86e755

Is there a way to fix this, either on AO's side or in the ASS maybe ?

Thanks in advance.

**Comment by Yay295** [comment]
Looks like it's auto-wrapping the line because it's too wide. The text is supposed to be 24px in height according to the subtitle styles, but there's not an easy way to set that in CSS, so the code uses a binary search method to find something that's close.

Interestingly my version of Firefox (which is a bit old) displays the subtitles correctly. In my version of Firefox it settles on a font size of 20.880846325167038px, while in Chrome it settles on a size of 21.742988227146814px. It's not much of a difference, but it's enough to push the length of that line from 354px to 369px. Since that subtitle file doesn't set a valid PlayResX or PlayResY, a default of 384x288 is chosen (this should be the same as in MPV). The subtitle style also has a left and right margin of 15px.

So we have 384px of video width, minus 15px from each side for the margin, leaving us with only 354px to put the line in. This happens to be the *exact* length of the line when it's short, so it fits; but when the line is bigger, it doesn't fit.

As for making it work, I'd just reduce the margins. 15px on each side is too much when the available area is only 384px.

*Note: The line in question starts at 3:10.85 and is near the end of the subtitle file.*

**Comment by AxelTerizaki** [comment]
Gotcha. Sorry for taking too much time to respond. We'll work with removing the margins :)

Thanks for the explanations, that was clear and precise, and exactly what we wanted to know more about.
